# Simple workflow for running all tests and formats

name: Test, Format, and Lint

on:
  pull_request:
    branches: ["master"]

  # Create a reusable workflow
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - run: npm run format-check
      - run: npm run lint-check
